/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceInput = IDL.Record({
  'estimatedDurationMinutes' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'basePrice' : IDL.Float64,
});
export const ServiceId = IDL.Nat;
export const Service = IDL.Record({
  'id' : ServiceId,
  'estimatedDurationMinutes' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'basePrice' : IDL.Float64,
});
export const CustomerInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const BikeDetails = IDL.Record({
  'bikeType' : IDL.Text,
  'brand' : IDL.Text,
  'issue' : IDL.Text,
});
export const BookingInput = IDL.Record({
  'customerInfo' : CustomerInfo,
  'date' : IDL.Text,
  'bikeDetails' : BikeDetails,
  'serviceId' : ServiceId,
  'timeSlot' : IDL.Text,
});
export const BookingId = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Booking = IDL.Record({
  'id' : BookingId,
  'customerInfo' : CustomerInfo,
  'status' : BookingStatus,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'bikeDetails' : BikeDetails,
  'serviceId' : ServiceId,
  'timeSlot' : IDL.Text,
});
export const BusinessHours = IDL.Record({
  'slotDurationMinutes' : IDL.Nat,
  'closeTime' : IDL.Text,
  'openTime' : IDL.Text,
});
export const WeeklyStats = IDL.Record({
  'weekStart' : IDL.Text,
  'bookingCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addService' : IDL.Func([ServiceInput], [Service], []),
  'blockDate' : IDL.Func([IDL.Text], [], []),
  'createBooking' : IDL.Func([BookingInput], [Booking], []),
  'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAvailableSlots' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getBlockedDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBusinessHours' : IDL.Func([], [BusinessHours], ['query']),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getWeeklyStats' : IDL.Func([IDL.Text], [WeeklyStats], ['query']),
  'listBookings' : IDL.Func(
      [IDL.Opt(BookingStatus)],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'setBusinessHours' : IDL.Func([BusinessHours], [], []),
  'unblockDate' : IDL.Func([IDL.Text], [], []),
  'updateBookingStatus' : IDL.Func(
      [IDL.Nat, BookingStatus],
      [IDL.Opt(Booking)],
      [],
    ),
  'updateService' : IDL.Func([IDL.Nat, ServiceInput], [IDL.Opt(Service)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceInput = IDL.Record({
    'estimatedDurationMinutes' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'basePrice' : IDL.Float64,
  });
  const ServiceId = IDL.Nat;
  const Service = IDL.Record({
    'id' : ServiceId,
    'estimatedDurationMinutes' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'basePrice' : IDL.Float64,
  });
  const CustomerInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BikeDetails = IDL.Record({
    'bikeType' : IDL.Text,
    'brand' : IDL.Text,
    'issue' : IDL.Text,
  });
  const BookingInput = IDL.Record({
    'customerInfo' : CustomerInfo,
    'date' : IDL.Text,
    'bikeDetails' : BikeDetails,
    'serviceId' : ServiceId,
    'timeSlot' : IDL.Text,
  });
  const BookingId = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Booking = IDL.Record({
    'id' : BookingId,
    'customerInfo' : CustomerInfo,
    'status' : BookingStatus,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'bikeDetails' : BikeDetails,
    'serviceId' : ServiceId,
    'timeSlot' : IDL.Text,
  });
  const BusinessHours = IDL.Record({
    'slotDurationMinutes' : IDL.Nat,
    'closeTime' : IDL.Text,
    'openTime' : IDL.Text,
  });
  const WeeklyStats = IDL.Record({
    'weekStart' : IDL.Text,
    'bookingCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addService' : IDL.Func([ServiceInput], [Service], []),
    'blockDate' : IDL.Func([IDL.Text], [], []),
    'createBooking' : IDL.Func([BookingInput], [Booking], []),
    'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAvailableSlots' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getBlockedDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBusinessHours' : IDL.Func([], [BusinessHours], ['query']),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getWeeklyStats' : IDL.Func([IDL.Text], [WeeklyStats], ['query']),
    'listBookings' : IDL.Func(
        [IDL.Opt(BookingStatus)],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'setBusinessHours' : IDL.Func([BusinessHours], [], []),
    'unblockDate' : IDL.Func([IDL.Text], [], []),
    'updateBookingStatus' : IDL.Func(
        [IDL.Nat, BookingStatus],
        [IDL.Opt(Booking)],
        [],
      ),
    'updateService' : IDL.Func([IDL.Nat, ServiceInput], [IDL.Opt(Service)], []),
  });
};

export const init = ({ IDL }) => { return []; };