/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BikeDetails {
  'bikeType' : string,
  'brand' : string,
  'issue' : string,
}
export interface Booking {
  'id' : BookingId,
  'customerInfo' : CustomerInfo,
  'status' : BookingStatus,
  'date' : string,
  'createdAt' : Timestamp,
  'bikeDetails' : BikeDetails,
  'serviceId' : ServiceId,
  'timeSlot' : string,
}
export type BookingId = bigint;
export interface BookingInput {
  'customerInfo' : CustomerInfo,
  'date' : string,
  'bikeDetails' : BikeDetails,
  'serviceId' : ServiceId,
  'timeSlot' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface BusinessHours {
  'slotDurationMinutes' : bigint,
  'closeTime' : string,
  'openTime' : string,
}
export interface CustomerInfo {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface Service {
  'id' : ServiceId,
  'estimatedDurationMinutes' : bigint,
  'name' : string,
  'description' : string,
  'basePrice' : number,
}
export type ServiceId = bigint;
export interface ServiceInput {
  'estimatedDurationMinutes' : bigint,
  'name' : string,
  'description' : string,
  'basePrice' : number,
}
export type Timestamp = bigint;
export interface WeeklyStats { 'weekStart' : string, 'bookingCount' : bigint }
export interface _SERVICE {
  'addService' : ActorMethod<[ServiceInput], Service>,
  'blockDate' : ActorMethod<[string], undefined>,
  'createBooking' : ActorMethod<[BookingInput], Booking>,
  'deleteService' : ActorMethod<[bigint], boolean>,
  'getAvailableSlots' : ActorMethod<[string], Array<string>>,
  'getBlockedDates' : ActorMethod<[], Array<string>>,
  'getBusinessHours' : ActorMethod<[], BusinessHours>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getWeeklyStats' : ActorMethod<[string], WeeklyStats>,
  'listBookings' : ActorMethod<[[] | [BookingStatus]], Array<Booking>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'setBusinessHours' : ActorMethod<[BusinessHours], undefined>,
  'unblockDate' : ActorMethod<[string], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], [] | [Booking]>,
  'updateService' : ActorMethod<[bigint, ServiceInput], [] | [Service]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];