/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ServiceId = bigint;
export type BookingId = bigint;
export interface WeeklyStats {
    weekStart: string;
    bookingCount: bigint;
}
export type Timestamp = bigint;
export interface ServiceInput {
    estimatedDurationMinutes: bigint;
    name: string;
    description: string;
    basePrice: number;
}
export interface BookingInput {
    customerInfo: CustomerInfo;
    date: string;
    bikeDetails: BikeDetails;
    serviceId: ServiceId;
    timeSlot: string;
}
export interface BusinessHours {
    slotDurationMinutes: bigint;
    closeTime: string;
    openTime: string;
}
export interface BikeDetails {
    bikeType: string;
    brand: string;
    issue: string;
}
export interface Service {
    id: ServiceId;
    estimatedDurationMinutes: bigint;
    name: string;
    description: string;
    basePrice: number;
}
export interface Booking {
    id: BookingId;
    customerInfo: CustomerInfo;
    status: BookingStatus;
    date: string;
    createdAt: Timestamp;
    bikeDetails: BikeDetails;
    serviceId: ServiceId;
    timeSlot: string;
}
export interface CustomerInfo {
    name: string;
    email: string;
    phone: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed"
}
export interface backendInterface {
    addService(input: ServiceInput): Promise<Service>;
    blockDate(date: string): Promise<void>;
    createBooking(input: BookingInput): Promise<Booking>;
    deleteService(id: bigint): Promise<boolean>;
    getAvailableSlots(date: string): Promise<Array<string>>;
    getBlockedDates(): Promise<Array<string>>;
    getBusinessHours(): Promise<BusinessHours>;
    getService(id: bigint): Promise<Service | null>;
    getWeeklyStats(weekStart: string): Promise<WeeklyStats>;
    listBookings(statusFilter: BookingStatus | null): Promise<Array<Booking>>;
    listServices(): Promise<Array<Service>>;
    setBusinessHours(hours: BusinessHours): Promise<void>;
    unblockDate(date: string): Promise<void>;
    updateBookingStatus(id: bigint, newStatus: BookingStatus): Promise<Booking | null>;
    updateService(id: bigint, input: ServiceInput): Promise<Service | null>;
}
import type { BikeDetails as _BikeDetails, Booking as _Booking, BookingId as _BookingId, BookingStatus as _BookingStatus, CustomerInfo as _CustomerInfo, Service as _Service, ServiceId as _ServiceId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addService(arg0: ServiceInput): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0);
            return result;
        }
    }
    async blockDate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockDate(arg0);
            return result;
        }
    }
    async createBooking(arg0: BookingInput): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteService(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getAvailableSlots(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots(arg0);
            return result;
        }
    }
    async getBlockedDates(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedDates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedDates();
            return result;
        }
    }
    async getBusinessHours(): Promise<BusinessHours> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessHours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessHours();
            return result;
        }
    }
    async getService(arg0: bigint): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyStats(arg0: string): Promise<WeeklyStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyStats(arg0);
            return result;
        }
    }
    async listBookings(arg0: BookingStatus | null): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookings(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookings(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return result;
        }
    }
    async setBusinessHours(arg0: BusinessHours): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBusinessHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBusinessHours(arg0);
            return result;
        }
    }
    async unblockDate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockDate(arg0);
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateService(arg0: bigint, arg1: ServiceInput): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    customerInfo: _CustomerInfo;
    status: _BookingStatus;
    date: string;
    createdAt: _Timestamp;
    bikeDetails: _BikeDetails;
    serviceId: _ServiceId;
    timeSlot: string;
}): {
    id: BookingId;
    customerInfo: CustomerInfo;
    status: BookingStatus;
    date: string;
    createdAt: Timestamp;
    bikeDetails: BikeDetails;
    serviceId: ServiceId;
    timeSlot: string;
} {
    return {
        id: value.id,
        customerInfo: value.customerInfo,
        status: from_candid_BookingStatus_n3(_uploadFile, _downloadFile, value.status),
        date: value.date,
        createdAt: value.createdAt,
        bikeDetails: value.bikeDetails,
        serviceId: value.serviceId,
        timeSlot: value.timeSlot
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n1(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus | null): [] | [_BookingStatus] {
    return value === null ? candid_none() : candid_some(to_candid_BookingStatus_n7(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
